#!/bin/bash
dconf load /org/gnome/shell/extensions/gestureImprovements/ <<END
[/]
default-overview=true
default-session-workspace=true
touchpad-pinch-speed=2.0
enable-alttab-gesture=false
allow-minimize-window=true
touchpad-speed-scale=1.25
END
gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell --method org.gnome.Shell.Extensions.InstallRemoteExtension 'gestureImprovements@gestures'
