#!/bin/bash
dconf write /org/gnome/shell/extensions/just-perfection/top-panel-position 0
dconf write /org/gnome/shell/extensions/just-perfection/notification-banner-position 2
dconf reset /org/gnome/shell/extensions/dash-to-dock/show-apps-at-top
dconf reset /org/gnome/shell/extensions/custom-hot-corners-extended/monitor-0-bottom-left-0/action
dconf reset /org/gnome/shell/extensions/custom-hot-corners-extended/monitor-0-bottom-right-0/action
dconf reset /org/gnome/shell/extensions/custom-hot-corners-extended/monitor-0-top-left-0/action
gnome-extensions list | grep -q babar@fthx && gnome-extensions enable babar@fthx
