#!/bin/bash
case $1 in
press-powerbtn-to-shutdown)
    gsettings set org.gnome.settings-daemon.plugins.power power-button-action interactive
    ;;
restrict-alttab-to-current-app)
    gsettings set org.gnome.shell.app-switcher current-workspace-only true
    ;;
press-super-d-to-show-desktop)
    gsettings set org.gnome.desktop.wm.keybindings show-desktop "['<Super>d']"
    ;;
show-process-tree-in-system-monitor)
    dconf write /org/gnome/gnome-system-monitor/show-dependencies true
    ;;
*)
    echo "Please report the error '$1' for author!"
    ;;
esac
