#!/bin/bash
case $1 in
touchpad-tap-to-click)
    gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
    ;;
resize-window-by-superkey-and-rightclk-drag)
    gsettings set org.gnome.desktop.wm.preferences resize-with-right-button true
    ;;
*)
    echo "Please report the error '$1' for author!"
    ;;
esac
