#!/bin/bash

# 触摸板轻触发出单机信号
./enable touchpad-tap-to-click

# Super 键 + 右键拖拽控制窗口大小
./enable resize-window-by-superkey-and-rightclk-drag

# 按电源键按钮关机
# ./config press-powerbtn-to-shutdown

# 限制 Alt + Tab 仅在同应用内切换。应用间切换按 Alt + `
./config restrict-alttab-to-current-app

# 按 Super + D 显示桌面
./config press-super-d-to-show-desktop

# 显示进程树
./config show-process-tree-in-system-monitor

# 不要在全局搜索中出现干扰人的 emoji 等字符结果
./patch no-redundant-char-searchresult

# 显示窗口标题栏的最小最大化按钮
./patch add-minmaxbtn-to-windowbar

# 省去 60s 关机确认
./patch skip-confirm-before-60s-shutdown-confirm

# Alt + ` 外观优化
./patch optimize-alt-grave-app-switcher-appearance

# 在顶栏显示电池百分比、星期几、日历的周序
./patch show-batterypercentage-weekday-weekdate-in-top-panel

# 使用推荐的快捷键组合
cat recommend-keymap.dconf | dconf load /
